apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gcs-fuse-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: gcs-fuse-per
  endpoints:
  - port: app-metrics
    interval: 15s
    path: /metrics  