apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""
  mountOptions:
    - implicit-dirs
    - file-cache:enable-parallel-downloads:true
    - file-cache:max-size-mb:-1
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: gke-bucket-mount

