apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""
  mountOptions:
    - only-dir=data
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <BucketName>

